### PR TITLE
PIO can upload firmware

### PR DESCRIPTION
**Pull request by GMagician**
Let'PIO ide upload firmware

### CODE REVIEW

**Review by technik-gegg — APPROVED** [review]

**Comment by technik-gegg** [comment]
At a closer look...
Ain't the build environment named wrong for that? [env:BIGTREE_SKR_MINI_E3_**SD**_20]

**Comment by GMagician** [comment]
That's the board I have and I tested the upload, don't know real name...maybe just 'e3_20'?
Edit: I just uploaded firmware, not yet "tested" everything. I just uploaded code to see if board was working

**Comment by technik-gegg** [comment]
Sure. What I mean is, does it make sense to rename it (or better create a new env - which might confuse somebody) or just leave it as is, since it offers both options?

**Comment by technik-gegg** [comment]
Nahh... forget it. I don't want to take care of yet another environment which is the same except this one line ;o).

**Comment by GMagician** [comment]
This doesn't change anything to previous environment. This let U select the button in ide to "upload" compiled code.
upload method is supported by all E3 2.0 boards, it's another way to load firmware (other than SD)

**Comment by technik-gegg** [comment]
I know. This method didn't work on the SKR mini, so I moved on to "SD only" to keep it somewhat consistent over all build envs.

**Comment by GMagician** [comment]
Yep but why not use it where possible, just don't say around you can. Smart people will use it, other will proceed with common SD update....

**Pull request merged**
