### PR TITLE
Common code style

### PR DESCRIPTION
**Pull request by GMagician**
Hi, I'm wondering it may be accepted such uniformed code styling inside program, I learned this style from Marlin, where I'm used to. Please note `servotick_t` it should be long in avr AFAIK and I see some mix uint32/unsigned int.

Before going on I need your "approval", no offence if you are used to a different style and this will be discarded

- Tab is always 2
- use ifdef where possible
- use nullptr
- create common macro to reduce #if in code
- always use "#pragma once" in include files

### CODE REVIEW

**Comment by technik-gegg** [comment]
Please stop  any code reviews/changes on this version. It's pretty worthless since the next release is going to be so much different.

BTW: I'm not going to discuss or modify any tab sizes or tab vs. spaces. This is purely subjective and doesn't do anything to improve the code.

**Comment by GMagician** [comment]
Stopped!

**Comment by technik-gegg** [comment]
I may publishe the new release this weekend - still got some testing to do. After this, your help is very appreciated.

**Comment by GMagician** [comment]
> BTW: I'm not going to discuss or modify any tab sizes or tab vs. spaces. This is purely subjective and doesn't do anything to improve the code.

No discussion about tab spacing but only one style over all program, that was main purpose.

**Pull request closed without merging**
