### PR TITLE
Split into hal

### PR DESCRIPTION
**Pull request by GMagician**
These changes aims to fix esp32 compiling and to start splitting code into an HAL logic.
More code needs to be modified but it's a start

### CODE REVIEW

**Comment by GMagician** [comment]
ESP32 needs a fix in leonerd oled library to be reapply compiled

**Comment by technik-gegg** [comment]
Any chance you test this on a real device before I merge? I'm a bit out of ressources right now.
Added conditional compile to LeoNerd's library for ESP32.

**Comment by GMagician** [comment]
Not soon. I don't have any smuff ready (waiting parts)

**Comment by GMagician** [comment]
Rebased to V2.19

**Pull request merged**
