### PR TITLE
[WIP] Add support for FYSETC AIOII

### PR DESCRIPTION
**Pull request by sl1pkn07**
https://wiki.fysetc.com/AIO_II
https://github.com/FYSETC/AIO_II

pin mapping based on Marlin pins defined for this board
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32f1/pins_FYSETC_AIO_II.h

i also add a platformio script (taked from marlin) for upload the firmware in this board via USB and Stm32flash (like do en marlin and say in the fysetc wiki)

the displya have RGB backlit(?)

Status: build and push to board OK, but the LCD not work. sound 2 tones in the buzzer, wait some secons, and play again a melody. the BED pin is ON

### CODE REVIEW

**Comment by technik-gegg** [comment]
Thank you for contributing.

Let's sort out the issues before we merge.

1. The buzzer signals a failure reading the config from the SD-Card (which the display would have told you likewise). 
Make sure you've copied the configuration file to the devices SD-Card before you boot it up.

2. The display (LX-12864B11 according to the circuit diagram) is supposed to be of type **ST7567**, very similar if not the same as on the Wanhao i3 mini board - at least that's what [sources on the internet say](https://github.com/olikraus/u8g2/issues/1042). So you may try that constructor instead of the **UC1701**...
_Another thing to take into account:_
The SKR mini is wired to run the display on **SPI3**, which is not supported through the default U8G2 library. Hence, I've added a code snippet in **SMuFFtools.cpp** around line 324, which overwrites the U8G2 library method for the 2nd SPI and routes it to SPI3.
I'm not convinced that this code snippet does affect the init of the AIOII's display, because it's supposed to be called only if you use a display constructor addressing the 2nd SPI (those with **_2ND_** in the method name).
Although, you may check this out, if the ST7567 constructor doesn't init the display successfully and add another #ifndef to ensure this snippet isn't being used on the **AIOII**.

**Comment by sl1pkn07** [comment]
the LCD is connected to SPI1

Screenshot_20200517_123553
Screenshot_20200517_123913
Screenshot_20200517_123936


so i've added

~~~patch
diff --git a/src/SMuFFtools.cpp b/src/SMuFFtools.cpp
index dcf5f78..9c56f24 100644
--- a/src/SMuFFtools.cpp
+++ b/src/SMuFFtools.cpp
@@ -322,7 +322,7 @@ uint8_t u8x8_GetMenuEvent(u8x8_t *u8x8)
 }
 
 #ifdef __STM32F1__
-  #ifndef USE_TWI_DISPLAY
+  #if !defined(USE_TWI_DISPLAY) && !defined(__BRD_FYSETC_AIOII)
 
 /* =========================================
 ATTENTION:
~~~

but still not works, or maybe workls, but i can't see the display because the blacklight is off, maybe because the RGB pins is off?
Screenshot_20200517_124307

I'm not coder, so i cant add a command to force on the RGB pins (my knowledge of arduino is because i touch marlin)

and about the SD. the card is formatted (fat32) and with the file SMUFF.CFG (capital letters) into the SD

greetings

**Comment by technik-gegg** [comment]
Let me just repeat what I wrote:
2. The display (LX-12864B11 according to the circuit diagram) is supposed to be of type **ST7567**, very similar if not the same as on the Wanhao i3 mini board - at least that's what sources on the internet say. So you may try that constructor instead of the **UC1701**...

Have you tried that?

**Comment by sl1pkn07** [comment]
yes, the same like the wanhao board, and do the same

**Comment by technik-gegg** [comment]
Then it has to have a different controller chip. 
Looking at the Marlin DOGM LCD codes, there are just a few of them supported:
 - ST7920
 - ST7565
 - UC1701
 - SSD1306

You may try one of them, except the SSD1306, since this is the I2C OLED.

To turn on the LEDs you need something like this:

pinMode(RGB_LED_R_PIN, OUTPUT);
pinMode(RGB_LED_G_PIN, OUTPUT);
pinMode(RGB_LED_B_PIN, OUTPUT);

digitalWrite(RGB_LED_R_PIN, 1);
digitalWrite(RGB_LED_G_PIN, 1);
digitalWrite(RGB_LED_B_PIN, 1);

Which supposedly will give you a white backlight.
But even if the backlight is off, you're supposed to see something on the screen if the controller is initialized correctly.

**Comment by sl1pkn07** [comment]
tested with:
~~~
U8G2_ST7567_JLX12864_1_4W_HW_SPI = no
U8G2_ST7567_JLX12864_2_4W_HW_SPI = no
U8G2_ST7567_JLX12864_F_4W_HW_SPI = no
U8G2_ST7567_JLX12864_1_2ND_4W_HW_SPI = no
U8G2_ST7567_JLX12864_2_2ND_4W_HW_SPI = no
U8G2_ST7567_JLX12864_F_2ND_4W_HW_SPI = no
~~~

the estrange, if add this

~~~patch
diff --git a/src/SMuFF.cpp b/src/SMuFF.cpp
index 262bf44..e8a9d8b 100644
--- a/src/SMuFF.cpp
+++ b/src/SMuFF.cpp
@@ -259,8 +259,19 @@ void setupDeviceName() {
 
 void setup() {
 
+// Turn on the LCD backlit in the FYSETC_AIOII
+#ifdef __BRD_FYSETC_AIOII
+  pinMode(RGB_LED_R_PIN, OUTPUT);
+  pinMode(RGB_LED_G_PIN, OUTPUT);
+  pinMode(RGB_LED_B_PIN, OUTPUT);
+
+  digitalWrite(RGB_LED_R_PIN, 1);
+  digitalWrite(RGB_LED_G_PIN, 1);
+  digitalWrite(RGB_LED_B_PIN, 1);
+#endif
+
 #ifdef __STM32F1__
-  #ifndef USE_TWI_DISPLAY
+  #if !defined(USE_TWI_DISPLAY) //&& !defined(__BRD_FYSETC_AIOII)
   afio_remap(AFIO_REMAP_SPI1);  // remap SPI3 to SPI1 if a "normal" display is being used
 
   if(DEBUG_OFF_PIN != -1) { 
~~~

the two tones is disapears, and only sound the melody (but the display still not works)

**Comment by sl1pkn07** [comment]
~~~
U8G2_UC1701_MINI12864_1_4W_HW_SPI = no
U8G2_UC1701_MINI12864_2_4W_HW_SPI = no
U8G2_UC1701_MINI12864_F_4W_HW_SPI = no
U8G2_UC1701_MINI12864_1_2ND_4W_HW_SPI = no
U8G2_UC1701_MINI12864_2_2ND_4W_HW_SPI = no
U8G2_UC1701_MINI12864_F_2ND_4W_HW_SPI = no
~~~

i think is not other, because is the same display used for standlaone fysetc displays
https://github.com/FYSETC/Mini-12864-Panel


when you use `U8G2_UC1701_MINI12864_1_2ND_4W_HW_SPI`, what display you use?

**Comment by technik-gegg** [comment]
You maybe right that this it the same display, but have you read what it [says here](https://github.com/FYSETC/Mini-12864-Panel#firmware-config)?

The easiest way to find out which driver works is by using the U8G2 library Arduino example "full_buffer > GraphicsTest".
Simply uncomment the according constructor and run the example.
You don't have to test the "_ 1_2ND _" constructors, because those will use the SPI2 ifc instead of the SPI1 to control the LCD and will not be able to handle the display for sure.

**Comment by sl1pkn07** [comment]
i have test with 

~~~
#include <Arduino.h>
#include <SPI.h>
#include <U8g2lib.h>

#define RGB_LED_R_PIN       PB0
#define RGB_LED_G_PIN       PB6
#define RGB_LED_B_PIN       PB7
#define DSP_CS_PIN          PB5
#define DSP_DC_PIN          PA15
#define DSP_SCK             PA5
#define DSP_MISO            PA6
#define DSP_MOSI            PA7
#define DSP_RESET_PIN       PB4


/* Constructor */
U8G2_UC1701_MINI12864_1_4W_HW_SPI U8G2(U8G2_R0, /* cs=*/ DSP_CS_PIN, /* dc=*/ DSP_DC_PIN, /* reset=*/ DSP_RESET_PIN);

/* U8G2.begin() is required and will sent the setup/init sequence to the display */
void setup(void) {

  pinMode(RGB_LED_R_PIN, OUTPUT);
  pinMode(RGB_LED_G_PIN, OUTPUT);
  pinMode(RGB_LED_B_PIN, OUTPUT);

  digitalWrite(RGB_LED_R_PIN, 1);
  digitalWrite(RGB_LED_G_PIN, 1);
  digitalWrite(RGB_LED_B_PIN, 1);

  U8G2.begin();
}

/* draw something on the display with the `firstPage()`/`nextPage()` loop*/
void loop(void) {
  U8G2.firstPage();
  do {
    U8G2.setFont(u8g2_font_ncenB14_tr);
    U8G2.drawStr(0,20,"Hello World!");
  } while ( U8G2.nextPage() );
  delay(1000);
}
~~~

like say in https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#introduction, but not works

the board works as spected in baremetal marlin, also, marlin uses u8glib(https://github.com/MarlinFirmware/U8glib-HAL/archive/bugfix.zip) instead of u8g2

greetings

**Comment by technik-gegg** [comment]
I guess you still havent seen it. 
Let me quote from the link you posted:

> Firmware config
This screen driver is **ST7567** and is compatible with the marlin Mini panel. It has been tested well, but the following configuration is required.

Why do you still insist on using the UC1701 constructor?

Marlin doesn't use the U8glib, it uses a modified version of the base U8glib...
However, I'm not going to mess around with U8glib since it's officially outdated and has been replaced  by the U8G2 library.

**Comment by sl1pkn07** [comment]
i have tested uc and st, you see uc beacause is the latest i've tested

for example, with U8G2_ST7567_JLX12864_1_4W_HW_SPI

pictures:
<details>

IMG_20200517_170740
IMG_20200517_171042

</details>

**Comment by technik-gegg** [comment]
Maybe it makes more sense to put a request on Fysetc's AIOII github to figure out which controller it uses and if it's useable through the U8g2 lib first.
They should know best.

**Comment by sl1pkn07** [comment]
done

https://github.com/FYSETC/AIO_II/issues/5

**Comment by technik-gegg** [comment]
Have you tried this one?
U8G2_ST7567_ENH_DG128064_F_4W_HW_SPI

I've just tested it with the MKS-MINI12864 V2.0 display. Some source on the internet claim, this is the same controller as on the FYSETC displays.

**Comment by sl1pkn07** [comment]
tested rigth now, not works :/

**Comment by sl1pkn07** [comment]
@GerogeFu @eliwong ping?

**Comment by GerogeFu** [comment]
Sorry , i'm not familiar with this project, but the code for AIO board is here.  
https://github.com/FYSETC/Marlin-2.0.x-FYSETC/tree/AIO_II/TMC2208
And the actual screen chip is ST7565R , but should compatible with 1701

**Comment by GerogeFu** [comment]
And the marlin lcd driver file is here https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/dogm/u8g_dev_uc1701_mini12864_HAL.cpp

**Comment by technik-gegg** [comment]
@GerogeFu 
Thank you for all the informational links.

I have one question though: 
Have you ever tried / been able to run the AIOII board/display using the successor U8G2 library from olikraus?

According to the data you have provided, it's supposed to be initialized using either one of those constructors: 
- U8G2_UC1701_MINI12864_1_4W_HW_SPI
- U8G2_UC1701_MINI12864_F_4W_HW_SPI

I've just checked with the U8G2 library, that the init sequence is the is the same as described in the link https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/lcd/dogm/u8g_dev_uc1701_mini12864_HAL.cpp

**Comment by GerogeFu** [comment]
@technik-gegg 
I didn't test it with U8G2. If you want i can send you this board to finish this PR.

**Comment by technik-gegg** [comment]
@GerogeFu 
That'd be really nice. A hands-on approach often makes more sense than pure theory ;o)

**Comment by GerogeFu** [comment]
You need to spend 1 dollar
https://www.aliexpress.com/item/32846760668.html
And leave a message about this project , our salesman will check it with me.

**Comment by technik-gegg** [comment]
@GerogeFu 
Will do. Thank you for your effort.

**Comment by GerogeFu** [comment]
It's all right. Willing to support opensource project.

**Comment by GerogeFu** [comment]
@technik-gegg Sorry we didn't find your order. My email fzl@fysetc.com. Please check it with me.

**Review by technik-gegg — APPROVED** [review]
Added to 2.04

**Comment by sl1pkn07** [comment]
for the record. the LCD still not works

or i missing something?

greetings

**Comment by technik-gegg** [comment]
I haven't tested it yet...

Well, then I'm going to remove it again until I find some time to test ist fully.

**Comment by sl1pkn07** [comment]
ok. i manage to run the display!

IMG_20200614_163755

a make a little test. but few things not play well as expected

the first one is the encoder. seems need spin slowly for run. but not work all times. the button works as expected
the second one is the contrast. i have set in the SMUFF.CFG the contrast to 230. but seems is not changed when powerup/reboot. what is the maximun value?

greetings

**Comment by technik-gegg** [comment]
You shouldn't run the encoder without a cap because it dilutes the results. If it's more or less the same with a cap, change the "Steps-Per-Notch" value in SMuFF.cpp where it initializes the encoder:
encoder(ENCODER1_PIN, ENCODER2_PIN, ENCODER_BUTTON_PIN, 4);
Increment or decrement the last value.
The contrast must be between 60 and 250 in the config.

**Comment by sl1pkn07** [comment]
Hi

tested encoder values from 0 to 30 (+1 each try) i can't see any diference

and also test the contrast  in the CFG file from 60 to 250

any try is with poweroff the unit and remove the EEPROM.DAT form the SD if the only reset is keep the values on ram or something. no success

greetings

**Comment by technik-gegg** [comment]
Not sure about this.
As with all we know now, the AIO II bases on the Mini Panel. In the Mini Panel documentation it states clearly that [it can't handle the contrast](
https://github.com/FYSETC/Mini-12864-Panel#step4-add-the-codes-in-ultralcd_impl_dogmh).
So, I guess you have to live with it for now.

As for the encoder, try defining this in SMuFF.cpp:
```
#define ENC_DECODER = ENC_FLAKY
```
and see if  it changes anything.

**Comment by sl1pkn07** [comment]
Hi

is strange, because you "contrast dimmer" code in u8g2 issue works as expected

also, if edit this line

https://github.com/technik-gegg/SMuFF-1.1/blob/b85844f42f99e36cd66f7ca76e535b4fa02dcc0a/include/Config.h#L49

works, but not through CFG file


and about encoder

added  `#define ENC_DECODER ENC_FLAKY` into ClinckEncoder.h (dont ask me why, but only work if put the define in that file)

the turn of knob works, but only in one direction :/ (clockwise) (this is also strange, handle better the movements in anticlockwise direction, but the menu moves clockwise) 

greetings

**Comment by sl1pkn07** [comment]
Ok, encoder thing fixed. but not like the hack

Screenshot_20200625_235943

2 resistors, 10k, in each enc rotatory pin, and joined in 3.3v (pullup?)

no flaky hack (half steps), no steppernotch change. just works, on smuff

the only thing is, the fysetc mini12864 and anet A6 12864 (idk MKS mini12864) not have this pull up, and run OOTB. why?

greetings

**Comment by technik-gegg** [comment]
Can't tell for sure. 
In the Encoder code these pins are configured to be INPUT_PULLUP by default, so the internal pull up resistors are being used: 
```
#if defined (__STM32F1__)
  WiringPinMode configType = (pinsActive == LOW) ? INPUT_PULLUP : INPUT_PULLDOWN;
#else
  uint8_t configType = (pinsActive == LOW) ? INPUT_PULLUP : INPUT;
#endif
```
But this internal pull up might be not enough to read out a clear signal and hence it becomes flaky.
As the STM32 documentation states:
```
Each STM32 GPIO offers the possibility to select internal pull-up and pull-down (typical
value = 40 kOhm). Some STM32 applications may require to use an external pull-up
resistor.
```
BTW: You should check the voltage for those pull ups. Not every pin on the STM32 is 5V tolerant, therefore you should use 3.3V as the pull up source to be safe.

**Comment by sl1pkn07** [comment]
> BTW: You should check the voltage for those pull ups. Not every pin on the STM32 is 5V tolerant, therefore you should use 3.3V as the pull up source to be safe.

is actually 3.3v, i see the schemes again. all "+" pins for detectors is 3.3v, so is safe (edited the comment now)

**Pull request merged**
